apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    type: web 
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: alamalinux
    image: alamalinux:9
    command: ["sleep", "100"] #"/bin/sh", "-c", "while true; do sleep 30; done"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
