apiVersion: v1
kind: Deployment
metadata:
  name: multi-deployment
  labels:
    app: multi-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-pod
  template:
    metadata:
      labels:
        app: multi-pod
    spec:
      containers:
      - name: multi-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  multi-volume
            mountPath: /var/log/nginx
      - name: sidecar-container
        image: busybox:latest
        command: ["sleep", "3600"]
        volumeMounts:
          - name:  multi-volume
            mountPath: /mnt/vol
      volumes:
        - name:  multi-volume
          emptyDir: {}
            sizeLimit: 500Mi
