apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 8080 # container port
  type: ClusterIP
