# headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
  - port:  6379  #service port
    targetPort:  6379  # container port
    protocol: TCP  
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port:  6379  #serive port
      targetPort:  6379  #container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "redis-headless" # this should be head less service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: sathishdevops38/redis:v1
        readinessProbe:
          tcpSocket:
            port:  6379 
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port:  6379 
        volumeMounts:
        - name: redis
          mountPath: /data
  # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi